[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 1
via_ir = false
evm_version = "cancun"

[rpc_endpoints]
hashkey_testnet = "https://testnet.hsk.xyz"
hashkey_mainnet = "https://mainnet.hsk.xyz"
